---
title: "Preregistrtion"
author: "Friederike Vorwerk"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE,
                      cache.lazy=FALSE)
```

# Dependencies

```{r}
# package vector
packages <- c("ggplot2", "lmtest", "stats", "car")

# un-comment to install packages
# for (i in 1:length(packages)){install.packages(packages[i], character.only = T)
# }

# load packages
for (i in 1:length(packages)){
  library(packages[i], character.only = T)
}
```


#Hypothesis 1: Covariance Analysis
```{r}

mat <- matrix(c(-0.25,-0.25,-0.25-0.25))

contrasts(data$group) <- mat

# check normal distribution with histogram
ggplot(data, aes(x=symb_trust)) + geom_histogram()

#Estimate Model
symbgroup_model <- lm(symb_trust ~ group,
               data = data)

summary(symbgroup_model)
```
##Assumptions for Hypothesis 1
```{r}


```



#Hypothesis 2: model comparison, likelihood ratio test
```{r}
model0 <- glm(system_trust ~ 1, data=data)
model1 <- glm(system_trust ~ symbol_trust, data=data)

# Likelihood Ratio Test
lrtest(model0,model1)
```



#Hypothesis 3: linear regression
```{r}
#modeling
reactiontrust_model <- lm(reaction_data  ~ symb_trust, data = reaction_data)
summary(reactiontrust_model)
```
##Assumptions of Linear Regression
- linearity
- normality of residuals
- homoscedasticity
- independent errors

```{r}
###check linearity with scatterplot
ggplot(reaction_data, aes(x=symb_trust, y=reactiontimes)) + geom_point()

### check normal distribution with histogram
ggplot(reaction_data, aes(x=reactiontimes)) + geom_histogram()
```
##outliners and influential cases hypothesis 3
```{r}
#outliers
reaction_data$standardized_residuals <- rstandard(reactiontrust_model) # should be <|2|

# influential cases
reaction_data$cooks_distance <- cooks.distance(reactiontrust_model) # should be < 1
```
### then identify cases

###Homoscredasiticty
```{r}
# Breusch Pagan Test / Cook-Weisberg Test: non-significance is homoscedastic
ncvTest(reactiontrust_model)
```
